### PR TITLE
Create additional Arabic version of the app with srt download capabilities for the team

### PR DESCRIPTION
**Pull request by pverkind**
We can probably now delete both versions without the Arabic, and use the arabic-version.html (with arabic.js) and arabic-kitab-version.html (with arabic_kitab.js) as the default.

### CODE REVIEW

**Comment by sohailmerchant** [comment]
@pverkind we will need approval from Sarah on this.  I will send an email to her tonight and copy everyone in.

**Comment by pverkind** [comment]
OK, great! 
Just to be sure: I'm not proposing to give everyone access to the srt files, only to have the app with Arabic as the default. The Arabic app with srt links should go in the Quicklinks, for the team only.

**Comment by pverkind** [comment]
I have added another small feature in my last commit: the legend that explains what the different colours of dots mean, now also functions as a filter for the table.

**Comment by sohailmerchant** [comment]
> OK, great!
> Just to be sure: I'm not proposing to give everyone access to the srt files, only to have the app with Arabic as the default. The Arabic app with srt links should go in the Quicklinks, for the team only.

Okay I am confused. What do you mean by 'Arabic as the default'  I thought you want when user clicks the domain name they see the arabic version by default?

**Comment by pverkind** [comment]
Yes that's what I mean!

**Comment by pverkind** [comment]
I solved the problem with the Arabic letters in the PDF, but the pdfs still look bad... See issue #18 .

**Pull request merged**
